2025.05.19 17:29:44 ERROR C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: / (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 5: 'trans', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x00000207BB52A2C0>)
Traceback (most recent call last):
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 563, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 5: 'trans', expected 'endblock'. Did you forget to register or load this tag?
2025.05.19 17:29:44 ERROR C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET / HTTP/1.1" 500 177854 None
2025.05.19 17:39:45 ERROR C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: / (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError('Unknown argument for \'trans\' tag: \'авторизованного\'. The only options available are \'noop\', \'context\' "xxx", and \'as VAR\'.'), <traceback object at 0x000001F68F27CF40>)
Traceback (most recent call last):
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\templatetags\i18n.py", line 443, in do_translate
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Unknown argument for 'trans' tag: 'авторизованного'. The only options available are 'noop', 'context' "xxx", and 'as VAR'.
2025.05.19 17:39:45 ERROR C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET / HTTP/1.1" 500 180358 None
2025.05.19 17:53:35 ERROR C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/news/create/ (<class 'django.db.utils.OperationalError'>, OperationalError('database is locked'), <traceback object at 0x000001F68F5B7500>)
Traceback (most recent call last):
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\NewsPortal\news\views.py", line 74, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\edit.py", line 133, in form_valid
    self.object = form.save()
                  ^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\forms\models.py", line 554, in save
    self.instance.save()
  File "C:\Users\dimab\PycharmProjects\NewsPortal\NewsPortal\news\models.py", line 68, in save
    super().save(*args, **kwargs)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\base.py", line 892, in save
    self.save_base(
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\base.py", line 998, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\base.py", line 1161, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\base.py", line 1202, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: database is locked
2025.05.19 17:53:35 ERROR C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\servers\basehttp.py "POST /news/news/create/ HTTP/1.1" 500 194284 None
2025.05.19 17:54:33 ERROR C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/news/create/ (<class 'kombu.exceptions.OperationalError'>, OperationalError('Error 10061 connecting to localhost:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.'), <traceback object at 0x000001F68F9F1040>)
Traceback (most recent call last):
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\connection.py", line 357, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\connection.py", line 358, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\connection.py", line 730, in _connect
    raise err
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\connection.py", line 718, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\backends\redis.py", line 127, in reconnect_on_error
    yield
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\backends\redis.py", line 177, in _consume_from
    self._pubsub.subscribe(key)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\client.py", line 957, in subscribe
    ret_val = self.execute_command("SUBSCRIBE", *new_channels.keys())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\client.py", line 786, in execute_command
    self.connection = self.connection_pool.get_connection(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\connection.py", line 1422, in get_connection
    connection.connect()
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to localhost:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\connection.py", line 357, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\connection.py", line 358, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\connection.py", line 730, in _connect
    raise err
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\connection.py", line 718, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\kombu\connection.py", line 472, in _reraise_as_library_errors
    yield
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\app\base.py", line 800, in send_task
    self.backend.on_task_call(P, task_id)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\backends\redis.py", line 373, in on_task_call
    self.result_consumer.consume_from(task_id)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\backends\redis.py", line 169, in consume_from
    return self.start(task_id)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\backends\redis.py", line 147, in start
    self._consume_from(initial_task_id)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\backends\redis.py", line 176, in _consume_from
    with self.reconnect_on_error():
  File "C:\Users\dimab\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\backends\redis.py", line 130, in reconnect_on_error
    self._ensure(self._reconnect_pubsub, ())
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\backends\redis.py", line 384, in ensure
    return retry_over_time(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\kombu\utils\functional.py", line 318, in retry_over_time
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\backends\redis.py", line 106, in _reconnect_pubsub
    metas = self.backend.client.mget(self.subscribed_to)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\commands\core.py", line 2009, in mget
    return self.execute_command("MGET", *args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\connection.py", line 1422, in get_connection
    connection.connect()
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to localhost:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\NewsPortal\news\views.py", line 74, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\edit.py", line 133, in form_valid
    self.object = form.save()
                  ^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\forms\models.py", line 555, in save
    self._save_m2m()
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\forms\models.py", line 536, in _save_m2m
    f.save_form_data(self.instance, cleaned_data[f.name])
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\fields\related.py", line 1969, in save_form_data
    getattr(instance, self.attname).set(data)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1352, in set
    self.add(*new_objs, through_defaults=through_defaults)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1253, in add
    self._add_items(
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1563, in _add_items
    signals.m2m_changed.send(
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\NewsPortal\news\signals.py", line 35, in notify_about_new_post
    send_news_notification.delay(instance.id)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\app\task.py", line 444, in delay
    return self.apply_async(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\app\task.py", line 594, in apply_async
    return app.send_task(
           ^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\app\base.py", line 798, in send_task
    with P.connection._reraise_as_library_errors():
  File "C:\Users\dimab\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\kombu\connection.py", line 476, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: Error 10061 connecting to localhost:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
2025.05.19 17:55:07 ERROR C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/news/create/ (<class 'django.db.utils.OperationalError'>, OperationalError('database is locked'), <traceback object at 0x000001F68F520CC0>)
Traceback (most recent call last):
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\NewsPortal\news\views.py", line 74, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\edit.py", line 133, in form_valid
    self.object = form.save()
                  ^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\forms\models.py", line 554, in save
    self.instance.save()
  File "C:\Users\dimab\PycharmProjects\NewsPortal\NewsPortal\news\models.py", line 68, in save
    super().save(*args, **kwargs)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\base.py", line 892, in save
    self.save_base(
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\base.py", line 998, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\base.py", line 1161, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\base.py", line 1202, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: database is locked
2025.05.19 17:55:07 ERROR C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\servers\basehttp.py "POST /news/news/create/ HTTP/1.1" 500 194686 None
2025.05.19 17:55:40 ERROR C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/news/create/ (<class 'django.db.utils.OperationalError'>, OperationalError('database is locked'), <traceback object at 0x000001F68FB57980>)
Traceback (most recent call last):
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\NewsPortal\news\views.py", line 74, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\edit.py", line 133, in form_valid
    self.object = form.save()
                  ^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\forms\models.py", line 554, in save
    self.instance.save()
  File "C:\Users\dimab\PycharmProjects\NewsPortal\NewsPortal\news\models.py", line 68, in save
    super().save(*args, **kwargs)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\base.py", line 892, in save
    self.save_base(
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\base.py", line 998, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\base.py", line 1161, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\base.py", line 1202, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: database is locked
2025.05.19 17:55:40 ERROR C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\servers\basehttp.py "POST /news/news/create/ HTTP/1.1" 500 195094 None
2025.05.19 17:58:12 ERROR C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/news/create/ (<class 'kombu.exceptions.OperationalError'>, OperationalError('Error 10061 connecting to localhost:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.'), <traceback object at 0x0000028699A4F340>)
Traceback (most recent call last):
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\connection.py", line 357, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\connection.py", line 358, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\connection.py", line 730, in _connect
    raise err
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\connection.py", line 718, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\backends\redis.py", line 127, in reconnect_on_error
    yield
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\backends\redis.py", line 177, in _consume_from
    self._pubsub.subscribe(key)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\client.py", line 957, in subscribe
    ret_val = self.execute_command("SUBSCRIBE", *new_channels.keys())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\client.py", line 786, in execute_command
    self.connection = self.connection_pool.get_connection(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\connection.py", line 1422, in get_connection
    connection.connect()
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to localhost:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\connection.py", line 357, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\connection.py", line 358, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\connection.py", line 730, in _connect
    raise err
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\connection.py", line 718, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\kombu\connection.py", line 472, in _reraise_as_library_errors
    yield
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\app\base.py", line 800, in send_task
    self.backend.on_task_call(P, task_id)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\backends\redis.py", line 373, in on_task_call
    self.result_consumer.consume_from(task_id)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\backends\redis.py", line 169, in consume_from
    return self.start(task_id)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\backends\redis.py", line 147, in start
    self._consume_from(initial_task_id)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\backends\redis.py", line 176, in _consume_from
    with self.reconnect_on_error():
  File "C:\Users\dimab\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\backends\redis.py", line 130, in reconnect_on_error
    self._ensure(self._reconnect_pubsub, ())
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\backends\redis.py", line 384, in ensure
    return retry_over_time(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\kombu\utils\functional.py", line 318, in retry_over_time
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\backends\redis.py", line 106, in _reconnect_pubsub
    metas = self.backend.client.mget(self.subscribed_to)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\commands\core.py", line 2009, in mget
    return self.execute_command("MGET", *args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\connection.py", line 1422, in get_connection
    connection.connect()
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\redis\connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to localhost:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\NewsPortal\news\views.py", line 74, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\views\generic\edit.py", line 133, in form_valid
    self.object = form.save()
                  ^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\forms\models.py", line 555, in save
    self._save_m2m()
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\forms\models.py", line 536, in _save_m2m
    f.save_form_data(self.instance, cleaned_data[f.name])
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\fields\related.py", line 1969, in save_form_data
    getattr(instance, self.attname).set(data)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1352, in set
    self.add(*new_objs, through_defaults=through_defaults)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1253, in add
    self._add_items(
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1563, in _add_items
    signals.m2m_changed.send(
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\NewsPortal\news\signals.py", line 35, in notify_about_new_post
    send_news_notification.delay(instance.id)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\app\task.py", line 444, in delay
    return self.apply_async(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\app\task.py", line 594, in apply_async
    return app.send_task(
           ^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\celery\app\base.py", line 798, in send_task
    with P.connection._reraise_as_library_errors():
  File "C:\Users\dimab\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\kombu\connection.py", line 476, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: Error 10061 connecting to localhost:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
2025.05.19 21:35:05 ERROR C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/ (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'category_list' not found. 'category_list' is not a valid view function or pattern name."), <traceback object at 0x000002716813EA40>)
Traceback (most recent call last):
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\templatetags\cache.py", line 53, in render
    value = self.nodelist.render(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'category_list' not found. 'category_list' is not a valid view function or pattern name.
2025.05.19 21:35:05 ERROR C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/ HTTP/1.1" 500 251498 None
2025.05.19 21:37:25 ERROR C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/ (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'category_list' not found. 'category_list' is not a valid view function or pattern name."), <traceback object at 0x000002B941DAEC40>)
Traceback (most recent call last):
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\templatetags\cache.py", line 53, in render
    value = self.nodelist.render(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'category_list' not found. 'category_list' is not a valid view function or pattern name.
2025.05.19 21:37:25 ERROR C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/ HTTP/1.1" 500 251498 None
2025.05.19 21:37:27 ERROR C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/ (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'category_list' not found. 'category_list' is not a valid view function or pattern name."), <traceback object at 0x000002B941FF0EC0>)
Traceback (most recent call last):
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\templatetags\cache.py", line 53, in render
    value = self.nodelist.render(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'category_list' not found. 'category_list' is not a valid view function or pattern name.
2025.05.19 21:37:27 ERROR C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/ HTTP/1.1" 500 251498 None
2025.05.19 21:37:44 ERROR C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/ (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'category_list' not found. 'category_list' is not a valid view function or pattern name."), <traceback object at 0x000001EC350F09C0>)
Traceback (most recent call last):
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\templatetags\cache.py", line 53, in render
    value = self.nodelist.render(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'category_list' not found. 'category_list' is not a valid view function or pattern name.
2025.05.19 21:37:44 ERROR C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/ HTTP/1.1" 500 251498 None
2025.05.19 21:45:32 ERROR C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/news/create/ (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Could not parse the remainder: '}{%' from ''Создать'}{%'"), <traceback object at 0x0000018DBB9779C0>)
Traceback (most recent call last):
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\defaulttags.py", line 976, in do_if
    nodelist = parser.parse(("endif",))
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\templatetags\i18n.py", line 403, in do_translate
    message_string = parser.compile_filter(bits[1])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 605, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\template\base.py", line 706, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '}{%' from ''Создать'}{%'
2025.05.19 21:45:32 ERROR C:\Users\dimab\PycharmProjects\NewsPortal\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/news/create/ HTTP/1.1" 500 218056 None
